---
repository: abhishek7389/hackathon-template-jekyll
include: ["index.html", "_events",]

# Homepage settings
splash_title: 'MLH Local Hack Day: Build'
splash_subtitle: 'Collebaration fist, code second'
homepage_banner_image: photos/hackday.png
display_ad: true



footer-description: "uild your way to greatness all week long at LHD: Build by completing challenges both big and small. You’ll expand your network, skillset, and hacker portfolio, and earn yourself rewards."


# Links for the navbar
navs:
  -
    name: Home
    link: "/#top"
  -
    name: Events
    link: "/#future-events"
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"


# Social media links included on the splash page
socials:
  -
    icon: "facebook-white.svg"
    name: Facebook
    url: "https://www.facebook.com/MajorLeagueHacking/"
  -
    icon: "twitter.svg"
    name: Twitter
    url: "https://twitter.com/MLHacks?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
  -
    icon: "github-mark.png"
    name: GitHub
    url: "https://github.com/MLH"

email: hi@mlh.io


collections:
  events:
    output: true
    permalink: /:slug


sass:
  style: compressed
  sass_dir: _sass
